# Neural Networks with Keras for classification
----

In this notebook, we will define our first neural network in `tensorflow` and `keras` and train it on the same data as in the first notebook. We start by importing some libraries:

In [1]:
import numpy as np
from sklearn.datasets import load_iris

To limit GPU memory usage, we initialize TensorFlow first:

In [2]:
import tensorflow as tf

Now load the keras modules:

In [3]:
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.utils import np_utils
from keras.callbacks import TensorBoard

## Loading dataset
----
We start with the same dataset (Iris) as in the first example:

In [4]:
iris = load_iris()
X = iris.data
y = iris.target

## Splitting into training and test data
----
Again, we have to split the data into training and test set:

In [5]:
from sklearn.model_selection import train_test_split

train_X, test_X, train_y, test_y = train_test_split(X, y, train_size=0.5, random_state=0)

## One-hot encoding
----

The scikit-learn classifier accepts strings as different classes. For neural networks, the classes need to be one-hot encoded. This means that we have to generate a binary mask holding the ground truth labels.

For this, pre-defined functions exist:

In [6]:
from keras.utils import to_categorical

train_y_ohe = to_categorical(train_y, 3)
test_y_ohe= to_categorical(test_y, 3)

Now we can look at what our data looks like hot-encoded:

In [7]:
print(train_y[:3,])

[0 2 1]


In [8]:
print(train_y_ohe[:3,])

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


## Defining a neural network in Keras
----
We use the sequential API in Keras and start by creating an instance of a keras model:

In [9]:
model = Sequential()

2023-11-29 14:46:08.027748: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


The different layers of the network are added step by step using the add() function. We first define the size of the input layer.

How many input neurons do we need?


In [10]:
INPUT_DIM = 4

We use a single dense layer with 16 neurons:

In [11]:
model.add(Dense(16, input_shape=(INPUT_DIM,)))

We also have to specify the activation function for this layer. We use a sigmoid function:

In [12]:
model.add(Activation('sigmoid'))

Next comes the output layer. How many output neurons do we need?


In [13]:
OUT_N = 3

Define the fully connected output layer:

In [14]:
model.add(Dense(OUT_N))

The activation function for the output layer is a softmax function:

In [15]:
model.add(Activation('softmax'))

We can look at a summary of the network architecture and the number of parameters:

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 16)                80        
                                                                 
 activation (Activation)     (None, 16)                0         
                                                                 
 dense_1 (Dense)             (None, 3)                 51        
                                                                 
 activation_1 (Activation)   (None, 3)                 0         
                                                                 
Total params: 131
Trainable params: 131
Non-trainable params: 0
_________________________________________________________________


## Compile model and specify metaparameters

Before we can fit the model to the data, we have to compile it to generate the corresponding TensorFlow graph that runs either on the CPU or GPU:

In [17]:
model.compile(optimizer='rmsprop', 
              loss='categorical_crossentropy',
              metrics=["accuracy"])


## Training the neural network
----
The training process can be started using the fit() function, as in scikit-learn. We have to specify the one-hot encoded training data, the number of epochs, batch size, and the validation data.

First, we specify and create a log dir to later look at the training process with TensorBoard:

In [18]:
import os

logdir = 'keras-nn'

if not os.path.exists(logdir): os.makedirs(logdir)

Now we specify number of epochs and batch size:

In [19]:
epochs = 500
batch_size = 4

Finally, we train (fit) the neural network. This has to be repeated every time you change the parameters:

In [20]:
history = model.fit(train_X, train_y_ohe, 
                    epochs=epochs, batch_size=batch_size,
                    validation_data=(test_X, test_y_ohe),
                    verbose=1,
                    callbacks=[TensorBoard(log_dir=logdir, histogram_freq=50)])

Epoch 1/500
19/19 [==============================] - 0s 8ms/step - loss: 1.1608 - accuracy: 0.2667 - val_loss: 1.0066 - val_accuracy: 0.4000
Epoch 2/500
19/19 [==============================] - 0s 2ms/step - loss: 1.0552 - accuracy: 0.2667 - val_loss: 0.9710 - val_accuracy: 0.4000
Epoch 3/500
19/19 [==============================] - 0s 5ms/step - loss: 0.9938 - accuracy: 0.4667 - val_loss: 0.9516 - val_accuracy: 0.6800
Epoch 4/500
19/19 [==============================] - 0s 2ms/step - loss: 0.9478 - accuracy: 0.6533 - val_loss: 0.9411 - val_accuracy: 0.6533
Epoch 5/500
19/19 [==============================] - 0s 2ms/step - loss: 0.9152 - accuracy: 0.7333 - val_loss: 0.9321 - val_accuracy: 0.6000
Epoch 6/500
19/19 [==============================] - 0s 2ms/step - loss: 0.8909 - accuracy: 0.7333 - val_loss: 0.9215 - val_accuracy: 0.6000
Epoch 7/500
19/19 [==============================] - 0s 2ms/step - loss: 0.8668 - accuracy: 0.7333 - val_loss: 0.9113 - val_accuracy: 0.6000
Epoch 8/500
1

Epoch 59/500
19/19 [==============================] - 0s 2ms/step - loss: 0.3398 - accuracy: 0.9333 - val_loss: 0.4216 - val_accuracy: 0.9733
Epoch 60/500
19/19 [==============================] - 0s 2ms/step - loss: 0.3361 - accuracy: 0.9200 - val_loss: 0.4138 - val_accuracy: 0.9867
Epoch 61/500
19/19 [==============================] - 0s 2ms/step - loss: 0.3330 - accuracy: 0.9467 - val_loss: 0.4090 - val_accuracy: 0.9867
Epoch 62/500
19/19 [==============================] - 0s 2ms/step - loss: 0.3289 - accuracy: 0.9467 - val_loss: 0.4066 - val_accuracy: 0.9867
Epoch 63/500
19/19 [==============================] - 0s 2ms/step - loss: 0.3269 - accuracy: 0.9467 - val_loss: 0.4033 - val_accuracy: 0.9867
Epoch 64/500
19/19 [==============================] - 0s 2ms/step - loss: 0.3211 - accuracy: 0.9467 - val_loss: 0.3969 - val_accuracy: 0.9867
Epoch 65/500
19/19 [==============================] - 0s 2ms/step - loss: 0.3179 - accuracy: 0.9467 - val_loss: 0.3943 - val_accuracy: 0.9867
Epoch 

19/19 [==============================] - 0s 2ms/step - loss: 0.1912 - accuracy: 0.9467 - val_loss: 0.2438 - val_accuracy: 0.9867
Epoch 117/500
19/19 [==============================] - 0s 2ms/step - loss: 0.1896 - accuracy: 0.9467 - val_loss: 0.2426 - val_accuracy: 0.9867
Epoch 118/500
19/19 [==============================] - 0s 2ms/step - loss: 0.1880 - accuracy: 0.9600 - val_loss: 0.2447 - val_accuracy: 0.9867
Epoch 119/500
19/19 [==============================] - 0s 2ms/step - loss: 0.1863 - accuracy: 0.9467 - val_loss: 0.2411 - val_accuracy: 0.9867
Epoch 120/500
19/19 [==============================] - 0s 2ms/step - loss: 0.1842 - accuracy: 0.9467 - val_loss: 0.2374 - val_accuracy: 0.9867
Epoch 121/500
19/19 [==============================] - 0s 2ms/step - loss: 0.1823 - accuracy: 0.9600 - val_loss: 0.2367 - val_accuracy: 0.9867
Epoch 122/500
19/19 [==============================] - 0s 2ms/step - loss: 0.1819 - accuracy: 0.9467 - val_loss: 0.2339 - val_accuracy: 0.9867
Epoch 123/500

19/19 [==============================] - 0s 2ms/step - loss: 0.1234 - accuracy: 0.9600 - val_loss: 0.1593 - val_accuracy: 0.9867
Epoch 174/500
19/19 [==============================] - 0s 2ms/step - loss: 0.1211 - accuracy: 0.9600 - val_loss: 0.1580 - val_accuracy: 0.9867
Epoch 175/500
19/19 [==============================] - 0s 2ms/step - loss: 0.1200 - accuracy: 0.9733 - val_loss: 0.1584 - val_accuracy: 0.9867
Epoch 176/500
19/19 [==============================] - 0s 2ms/step - loss: 0.1205 - accuracy: 0.9733 - val_loss: 0.1559 - val_accuracy: 0.9867
Epoch 177/500
19/19 [==============================] - 0s 2ms/step - loss: 0.1184 - accuracy: 0.9733 - val_loss: 0.1571 - val_accuracy: 0.9867
Epoch 178/500
19/19 [==============================] - 0s 2ms/step - loss: 0.1181 - accuracy: 0.9733 - val_loss: 0.1547 - val_accuracy: 0.9867
Epoch 179/500
19/19 [==============================] - 0s 2ms/step - loss: 0.1168 - accuracy: 0.9733 - val_loss: 0.1550 - val_accuracy: 0.9867
Epoch 180/500

19/19 [==============================] - 0s 2ms/step - loss: 0.0914 - accuracy: 0.9733 - val_loss: 0.1205 - val_accuracy: 0.9733
Epoch 231/500
19/19 [==============================] - 0s 2ms/step - loss: 0.0917 - accuracy: 0.9867 - val_loss: 0.1199 - val_accuracy: 0.9733
Epoch 232/500
19/19 [==============================] - 0s 2ms/step - loss: 0.0912 - accuracy: 0.9867 - val_loss: 0.1190 - val_accuracy: 0.9733
Epoch 233/500
19/19 [==============================] - 0s 2ms/step - loss: 0.0896 - accuracy: 0.9733 - val_loss: 0.1197 - val_accuracy: 0.9733
Epoch 234/500
19/19 [==============================] - 0s 2ms/step - loss: 0.0919 - accuracy: 0.9733 - val_loss: 0.1180 - val_accuracy: 0.9733
Epoch 235/500
19/19 [==============================] - 0s 2ms/step - loss: 0.0899 - accuracy: 0.9867 - val_loss: 0.1178 - val_accuracy: 0.9867
Epoch 236/500
19/19 [==============================] - 0s 2ms/step - loss: 0.0898 - accuracy: 0.9733 - val_loss: 0.1173 - val_accuracy: 0.9733
Epoch 237/500

19/19 [==============================] - 0s 2ms/step - loss: 0.0769 - accuracy: 0.9867 - val_loss: 0.1005 - val_accuracy: 0.9733
Epoch 288/500
19/19 [==============================] - 0s 2ms/step - loss: 0.0774 - accuracy: 0.9867 - val_loss: 0.1003 - val_accuracy: 0.9733
Epoch 289/500
19/19 [==============================] - 0s 2ms/step - loss: 0.0757 - accuracy: 0.9867 - val_loss: 0.0995 - val_accuracy: 0.9733
Epoch 290/500
19/19 [==============================] - 0s 2ms/step - loss: 0.0761 - accuracy: 0.9733 - val_loss: 0.0999 - val_accuracy: 0.9733
Epoch 291/500
19/19 [==============================] - 0s 2ms/step - loss: 0.0776 - accuracy: 0.9733 - val_loss: 0.0995 - val_accuracy: 0.9733
Epoch 292/500
19/19 [==============================] - 0s 2ms/step - loss: 0.0760 - accuracy: 0.9733 - val_loss: 0.0988 - val_accuracy: 0.9733
Epoch 293/500
19/19 [==============================] - 0s 2ms/step - loss: 0.0766 - accuracy: 0.9733 - val_loss: 0.0991 - val_accuracy: 0.9733
Epoch 294/500

19/19 [==============================] - 0s 2ms/step - loss: 0.0669 - accuracy: 0.9867 - val_loss: 0.0881 - val_accuracy: 0.9733
Epoch 345/500
19/19 [==============================] - 0s 2ms/step - loss: 0.0655 - accuracy: 0.9867 - val_loss: 0.0926 - val_accuracy: 0.9733
Epoch 346/500
19/19 [==============================] - 0s 2ms/step - loss: 0.0677 - accuracy: 1.0000 - val_loss: 0.0891 - val_accuracy: 0.9733
Epoch 347/500
19/19 [==============================] - 0s 2ms/step - loss: 0.0667 - accuracy: 0.9867 - val_loss: 0.0877 - val_accuracy: 0.9733
Epoch 348/500
19/19 [==============================] - 0s 2ms/step - loss: 0.0676 - accuracy: 0.9867 - val_loss: 0.0890 - val_accuracy: 0.9733
Epoch 349/500
19/19 [==============================] - 0s 2ms/step - loss: 0.0668 - accuracy: 0.9867 - val_loss: 0.0873 - val_accuracy: 0.9733
Epoch 350/500
19/19 [==============================] - 0s 2ms/step - loss: 0.0658 - accuracy: 0.9867 - val_loss: 0.0871 - val_accuracy: 0.9733
Epoch 351/500

19/19 [==============================] - 0s 2ms/step - loss: 0.0620 - accuracy: 0.9867 - val_loss: 0.0808 - val_accuracy: 0.9733
Epoch 402/500
19/19 [==============================] - 0s 2ms/step - loss: 0.0618 - accuracy: 0.9867 - val_loss: 0.0810 - val_accuracy: 0.9733
Epoch 403/500
19/19 [==============================] - 0s 2ms/step - loss: 0.0607 - accuracy: 0.9867 - val_loss: 0.0837 - val_accuracy: 0.9733
Epoch 404/500
19/19 [==============================] - 0s 2ms/step - loss: 0.0622 - accuracy: 0.9867 - val_loss: 0.0850 - val_accuracy: 0.9733
Epoch 405/500
19/19 [==============================] - 0s 2ms/step - loss: 0.0623 - accuracy: 0.9867 - val_loss: 0.0826 - val_accuracy: 0.9733
Epoch 406/500
19/19 [==============================] - 0s 2ms/step - loss: 0.0606 - accuracy: 0.9867 - val_loss: 0.0850 - val_accuracy: 0.9733
Epoch 407/500
19/19 [==============================] - 0s 2ms/step - loss: 0.0611 - accuracy: 0.9733 - val_loss: 0.0829 - val_accuracy: 0.9733
Epoch 408/500

19/19 [==============================] - 0s 2ms/step - loss: 0.0567 - accuracy: 0.9733 - val_loss: 0.0786 - val_accuracy: 0.9733
Epoch 459/500
19/19 [==============================] - 0s 2ms/step - loss: 0.0584 - accuracy: 0.9867 - val_loss: 0.0770 - val_accuracy: 0.9733
Epoch 460/500
19/19 [==============================] - 0s 2ms/step - loss: 0.0556 - accuracy: 0.9867 - val_loss: 0.0812 - val_accuracy: 0.9733
Epoch 461/500
19/19 [==============================] - 0s 2ms/step - loss: 0.0571 - accuracy: 0.9867 - val_loss: 0.0777 - val_accuracy: 0.9733
Epoch 462/500
19/19 [==============================] - 0s 2ms/step - loss: 0.0554 - accuracy: 0.9867 - val_loss: 0.0763 - val_accuracy: 0.9733
Epoch 463/500
19/19 [==============================] - 0s 2ms/step - loss: 0.0576 - accuracy: 0.9867 - val_loss: 0.0760 - val_accuracy: 0.9733
Epoch 464/500
19/19 [==============================] - 0s 2ms/step - loss: 0.0557 - accuracy: 0.9867 - val_loss: 0.0758 - val_accuracy: 0.9733
Epoch 465/500

Note that if you repeat the training process without recompiling the model, it will continue from the previous state of weights.

## Evaluate network performance
----
We extract loss and accuracy using the evaluate() function. We are using the same test data as for training: 

In [21]:
loss, accuracy = model.evaluate(test_X, test_y_ohe, verbose=0)
print("Accuracy = {:.2f}".format(accuracy))

Accuracy = 0.97


### TASK: Vary the metaparameters of the network and try to improve accuracy.
----
Which parameters seem to have a positive impact on accuracy?

# Look at the training progress

To look at the progress during training, we can use TensorBoard.